### ISSUE TITLE
Continues to save it to `~/data-store` instead in hidden folder

### ISSUE THREAD

**Issue by tunnckoCore** [helpers/helper-reflinks#1]
And that's strange, because it uses latest `data-store` version which defaults to `~/.data-store`?

**Comment by jonschlinkert** [comment]
was this resolved? with everything going on I can't remember lol

**Comment by tunnckoCore** [comment]
i think yes, i'll update verb soon and will recheck.

**Comment by jonschlinkert** [comment]
k thx

**Comment by tunnckoCore** [comment]
it seems solved :+1:

**Comment by jonschlinkert** [comment]
great thx for checking!
