### ISSUE TITLE
bug: wrong reflink format

### ISSUE THREAD

**Issue by jonschlinkert** [helpers/helper-reflinks#4]
I think the reflink template is using a `link` template because they're not the correct format. Sorry I'm trying to split this out into smaller, easier to manage libs.

**Comment by tunnckoCore** [comment]
Yea, noticed with latest verb. So should we just add `options.template` here to send it to `reflinks` or what you think? I can PR.

edit: mm yea, not only, there's a need for PR `reflinks` cuz makes links by default, not reflinks.
